name: 'Deploy Action'
description: 'Deploy to server'
inputs:
  environment:
    required: true
  deploy_dir:
    required: true
  server_key:
    required: true
  server_user:
    required: true
  server_host:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install & Build
      shell: bash
      run: |
        npm i
        npm run build

    - name: Deploy
      shell: bash
      env:
        SSH_KEY: ${{ inputs.server_key }}
        DEPLOY_USER: ${{ inputs.server_user }}
        DEPLOY_HOST: ${{ inputs.server_host }}
        DEPLOY_DIR: ${{ inputs.deploy_dir }}
      run: |
        # 部署脚本...
